# 02 · Construcción del dataset de evaluación Speech-to-Speech

**Entrada:** `data/processed/manifests/fleurs_sample.csv`

**Salida:** `data/processed/manifests/evaluation_v1.csv`

Convierte la muestra de FLEURS en el primer **golden dataset** del proyecto: audio + transcripción en español + traducción de referencia en inglés + split `dev/test`.

**Regla importante:** la traducción de referencia (ground truth) se introduce **manualmente**. Nunca debe generarse con el modelo de traducción que después será evaluado.

## 1. Entorno y dependencias

In [32]:
# --- Entorno: clonar repositorio (Colab) y configurar PROJECT_ROOT ---------
import os
import sys
from pathlib import Path

REPO_URL = "https://github.com/Setrox1250/Proyecto-IA-Traductor.git"
COLAB_REPO_DIR = Path("/content/Proyecto-IA-Traductor")

def _is_project_root(path: Path) -> bool:
    return (path / "src").is_dir() and (path / "requirements" / "dataset.txt").is_file()

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    if not COLAB_REPO_DIR.exists():
        !git clone {REPO_URL} {COLAB_REPO_DIR} 2>/dev/null || true
    if not COLAB_REPO_DIR.exists():
        raise SystemExit(
            "No se pudo clonar el repositorio.\n"
            "Si el repositorio es PRIVADO, Colab no puede clonarlo sin credenciales.\n"
            "Soluciones:\n"
            "  A) Hazlo PÚBLICO en GitHub: Settings -> General -> Danger Zone -> Change visibility.\n"
            "  B) Ejecuta la celda de autenticación con token (getpass) y vuelve a ejecutar esta celda."
        )
    PROJECT_ROOT = COLAB_REPO_DIR
else:
    # Ejecución local: buscar la raíz del proyecto subiendo por los padres
    def _find_local_project_root() -> Path:
        current = Path.cwd().resolve()
        for parent in [current] + list(current.parents):
            if _is_project_root(parent):
                return parent
        raise SystemExit(
            "No se encontró la raíz del proyecto.\n"
            "Ejecuta este notebook desde dentro del repositorio Proyecto-IA-Traductor."
        )
    PROJECT_ROOT = _find_local_project_root()

if not _is_project_root(PROJECT_ROOT):
    raise SystemExit(
        f"No se encontró la raíz del proyecto en {PROJECT_ROOT}.\n"
        "Revisa el clone del repositorio o ejecuta el notebook desde el directorio correcto."
    )

os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT =", PROJECT_ROOT)
print("Working directory:", os.getcwd())
print("Entorno inicializado correctamente.")

PROJECT_ROOT = /content/Proyecto-IA-Traductor
Working directory: /content/Proyecto-IA-Traductor
Entorno inicializado correctamente.

In [33]:
# --- SOLO si el repositorio es PRIVADO (opcional) -------------------------
# Si el clone de la celda anterior falló con "could not read Username",
# descomenta y ejecuta ESTA celda. Pedirá un token de acceso personal
# (fine-grained PAT con permiso Contents: Read-only). El token se ingresa en
# memoria en tiempo de ejecución y NO se guarda en el notebook.
# Luego vuelve a ejecutar la celda de bootstrap para continuar.
#
# import getpass
# token = getpass.getpass("GitHub fine-grained PAT (permiso Contents: Read): ")
# !git clone https://{token}@github.com/Setrox1250/Proyecto-IA-Traductor.git /content/Proyecto-IA-Traductor

In [34]:
requirements_file = PROJECT_ROOT / "requirements" / "dataset.txt"
if not requirements_file.exists():
    raise FileNotFoundError(f"requirements/dataset.txt no encontrado en {PROJECT_ROOT}")
%pip install --quiet -r requirements/dataset.txt

### 1.1 Imports y rutas

In [35]:
import pandas as pd
from IPython.display import display

from src.dataset import manifest as m

SEED = m.SEED
DEV_RATIO = m.DEV_RATIO
MANIFEST_PATH = m.FLEURS_MANIFEST_PATH
OUTPUT_PATH = m.EVALUATION_CSV
MANUAL_PATH = m.MANUAL_TRANSLATIONS_PATH

## 2. Cargar el manifest de FLEURS

In [36]:
manifest = m.load_manifest(MANIFEST_PATH)
print(f"Registros cargados: {len(manifest)}")
display(manifest)

Registros cargados: 20

,sample_id,speaker_id,audio_path,transcription_es,duration_sec,source
0,fleurs_es_419_0000,NaN,data/raw/audio/fleurs_es_419_0000.wav,En un extremo de la encuesta se ubica un 29 % ...,17.16,fleurs:es_419
1,fleurs_es_419_0001,NaN,data/raw/audio/fleurs_es_419_0001.wav,Las teorías de contenido se centran en buscar ...,6.36,fleurs:es_419
2,fleurs_es_419_0002,NaN,data/raw/audio/fleurs_es_419_0002.wav,Si bien las superficies que azotan los tornado...,10.92,fleurs:es_419
3,fleurs_es_419_0003,NaN,data/raw/audio/fleurs_es_419_0003.wav,"La ciudad se ubica junto a las cataratas, que ...",15.06,fleurs:es_419
4,fleurs_es_419_0004,NaN,data/raw/audio/fleurs_es_419_0004.wav,Se entiende por agricultura de subsistencia aq...,12.72,fleurs:es_419
5,fleurs_es_419_0005,NaN,data/raw/audio/fleurs_es_419_0005.wav,Ring también llegó a un acuerdo en el litigio ...,10.26,fleurs:es_419
6,fleurs_es_419_0006,NaN,data/raw/audio/fleurs_es_419_0006.wav,Lo único que le digo a la gente es que ustedes...,6.06,fleurs:es_419
7,fleurs_es_419_0007,NaN,data/raw/audio/fleurs_es_419_0007.wav,Esto también puede tomarse prestado de las pre...,21.48,fleurs:es_419
8,fleurs_es_419_0008,NaN,data/raw/audio/fleurs_es_419_0008.wav,Allí descubrieron el cadáver de Saroja Balasub...,11.28,fleurs:es_419
9,fleurs_es_419_0009,NaN,data/raw/audio/fleurs_es_419_0009.wav,"Sudáfrica, mejor cabeza de serie del torneo, c...",9.12,fleurs:es_419
10,fleurs_es_419_0010,NaN,data/raw/audio/fleurs_es_419_0010.wav,Ninguna alianza aérea abarca el cruce de los t...,9.78,fleurs:es_419
11,fleurs_es_419_0011,NaN,data/raw/audio/fleurs_es_419_0011.wav,Existen cámaras de películas con formato medio...,10.44,fleurs:es_419
12,fleurs_es_419_0012,NaN,data/raw/audio/fleurs_es_419_0012.wav,"El Sr. Costello sostuvo que, cuando la generac...",9.42,fleurs:es_419
13,fleurs_es_419_0013,NaN,data/raw/audio/fleurs_es_419_0013.wav,La luz y el calor que emana de las estrellas s...,12.60,fleurs:es_419
14,fleurs_es_419_0014,NaN,data/raw/audio/fleurs_es_419_0014.wav,"Por suerte, estoy bien, pero presencié una esc...",9.36,fleurs:es_419
15,fleurs_es_419_0015,NaN,data/raw/audio/fleurs_es_419_0015.wav,Si quiere viajar alrededor del mundo circunscr...,12.36,fleurs:es_419
16,fleurs_es_419_0016,NaN,data/raw/audio/fleurs_es_419_0016.wav,«Algunos estudios sugieren que la enfermedad d...,10.56,fleurs:es_419
17,fleurs_es_419_0017,NaN,data/raw/audio/fleurs_es_419_0017.wav,El juez le manifestó a Blake que era «práctica...,8.94,fleurs:es_419
18,fleurs_es_419_0018,NaN,data/raw/audio/fleurs_es_419_0018.wav,"Otra figura griega de renombre es Pitágoras, m...",12.66,fleurs:es_419
19,fleurs_es_419_0019,NaN,data/raw/audio/fleurs_es_419_0019.wav,"Por otra parte, es precisamente debido al elev...",9.48,fleurs:es_419

## 3. Traducciones de referencia manuales

Flujo recomendado:
1. La siguiente celda crea (si no existe) `data/processed/manifests/manual_translations.csv` con una fila por muestra.
2. En Colab se descarga ese CSV, se completa la columna `translation_en` y se vuelve a subir a la misma ruta.
3. Alternativamente, se pueden escribir las traducciones directamente en el dict de la sección 3.2.

El CSV **no se sobrescribe** en ejecuciones posteriores: solo se crea la primera vez.

In [37]:
manual_path = m.ensure_manual_translations_file(manifest)
print("Archivo de traducciones:", manual_path)

Archivo de traducciones: data/processed/manifests/manual_translations.csv

In [38]:
try:
    from google.colab import files
    files.download(str(manual_path))
    print("Descarga el CSV, complétalo y súbelo de vuelta a", manual_path)
except ImportError:
    print("No estás en Colab: edita el CSV directamente con tu editor.")

Descarga el CSV, complétalo y súbelo de vuelta a data/processed/manifests/manual_translations.csv

### 3.1 Cargar traducciones desde el CSV manual

In [39]:
translations = m.load_translations_dict()
print(f"Traducciones cargadas del CSV: {len(translations)} de {len(manifest)}")

Traducciones cargadas del CSV: 0 de 20

### 3.2 (Opcional) Traducciones directas en el notebook

Útil para pocas muestras. Descomenta una línea si quieres traducir aquí mismo.

In [40]:
manual_translations_extra: dict[str, str] = {}
# manual_translations_extra = {"fleurs_es_419_0000": "The dog is sleeping."}

### 3.3 Aplicar traducciones al manifest

In [41]:
translations.update(manual_translations_extra)
df = m.apply_translations(manifest, translations)
missing = df[df["translation_en"].str.strip() == ""]
print(f"Traducciones aplicadas: {len(translations)} de {len(df)}")
display(missing[["sample_id", "transcription_es", "translation_en"]])

Traducciones aplicadas: 0 de 20

,sample_id,transcription_es,translation_en
0,fleurs_es_419_0000,En un extremo de la encuesta se ubica un 29 % ...,
1,fleurs_es_419_0001,Las teorías de contenido se centran en buscar ...,
2,fleurs_es_419_0002,Si bien las superficies que azotan los tornado...,
3,fleurs_es_419_0003,"La ciudad se ubica junto a las cataratas, que ...",
4,fleurs_es_419_0004,Se entiende por agricultura de subsistencia aq...,
5,fleurs_es_419_0005,Ring también llegó a un acuerdo en el litigio ...,
6,fleurs_es_419_0006,Lo único que le digo a la gente es que ustedes...,
7,fleurs_es_419_0007,Esto también puede tomarse prestado de las pre...,
8,fleurs_es_419_0008,Allí descubrieron el cadáver de Saroja Balasub...,
9,fleurs_es_419_0009,"Sudáfrica, mejor cabeza de serie del torneo, c...",
10,fleurs_es_419_0010,Ninguna alianza aérea abarca el cruce de los t...,
11,fleurs_es_419_0011,Existen cámaras de películas con formato medio...,
12,fleurs_es_419_0012,"El Sr. Costello sostuvo que, cuando la generac...",
13,fleurs_es_419_0013,La luz y el calor que emana de las estrellas s...,
14,fleurs_es_419_0014,"Por suerte, estoy bien, pero presencié una esc...",
15,fleurs_es_419_0015,Si quiere viajar alrededor del mundo circunscr...,
16,fleurs_es_419_0016,«Algunos estudios sugieren que la enfermedad d...,
17,fleurs_es_419_0017,El juez le manifestó a Blake que era «práctica...,
18,fleurs_es_419_0018,"Otra figura griega de renombre es Pitágoras, m...",
19,fleurs_es_419_0019,"Por otra parte, es precisamente debido al elev...",

Si quedan filas sin traducir, la siguiente celda detendrá la ejecución: completa el CSV y vuelve a ejecutar el notebook desde la sección 3.

In [42]:
m.assert_complete_evaluation(df, audio_root=PROJECT_ROOT)
print("Todos los campos obligatorios están completos: audio, transcripción, traducción y duración.")

ValueError: El dataset de evaluación está incompleto:
 - hay traducciones de referencia vacías

## 4. Asignar split dev/test (70% / 30%)

La división es reproducible (semilla fija). Si existiera `speaker_id` se separarían grupos completos de hablante para evitar *leakage*; FLEURS no lo expone, así que aquí la división es por filas y así queda documentado.

In [43]:
df = m.assign_splits(df, dev_ratio=DEV_RATIO, seed=SEED)
display(m.split_distribution(df))

       count
split
dev       14
test       6

## 5. Estadísticas del dataset final

In [44]:
display(m.evaluate_manifest_stats(df))

               metric    value
0         num_samples   20.000
1  total_duration_sec  226.020
2   mean_duration_sec   11.301
3        num_speakers      NaN

## 6. Guardar el dataset de evaluación

Se ordenan las columnas canónicas del proyecto y se guarda en CSV (UTF-8).

In [45]:
m.save_evaluation_manifest(df, OUTPUT_PATH)
display(df)

Dataset de evaluación guardado en data/processed/manifests/evaluation_v1.csv

,sample_id,speaker_id,audio_path,transcription_es,duration_sec,source,translation_en,split
0,fleurs_es_419_0000,NaN,data/raw/audio/fleurs_es_419_0000.wav,En un extremo de la encuesta se ubica un 29 % ...,17.16,fleurs:es_419,,dev
1,fleurs_es_419_0001,NaN,data/raw/audio/fleurs_es_419_0001.wav,Las teorías de contenido se centran en buscar ...,6.36,fleurs:es_419,,test
2,fleurs_es_419_0002,NaN,data/raw/audio/fleurs_es_419_0002.wav,Si bien las superficies que azotan los tornado...,10.92,fleurs:es_419,,test
3,fleurs_es_419_0003,NaN,data/raw/audio/fleurs_es_419_0003.wav,"La ciudad se ubica junto a las cataratas, que ...",15.06,fleurs:es_419,,dev
4,fleurs_es_419_0004,NaN,data/raw/audio/fleurs_es_419_0004.wav,Se entiende por agricultura de subsistencia aq...,12.72,fleurs:es_419,,test
5,fleurs_es_419_0005,NaN,data/raw/audio/fleurs_es_419_0005.wav,Ring también llegó a un acuerdo en el litigio ...,10.26,fleurs:es_419,,dev
6,fleurs_es_419_0006,NaN,data/raw/audio/fleurs_es_419_0006.wav,Lo único que le digo a la gente es que ustedes...,6.06,fleurs:es_419,,dev
7,fleurs_es_419_0007,NaN,data/raw/audio/fleurs_es_419_0007.wav,Esto también puede tomarse prestado de las pre...,21.48,fleurs:es_419,,dev
8,fleurs_es_419_0008,NaN,data/raw/audio/fleurs_es_419_0008.wav,Allí descubrieron el cadáver de Saroja Balasub...,11.28,fleurs:es_419,,test
9,fleurs_es_419_0009,NaN,data/raw/audio/fleurs_es_419_0009.wav,"Sudáfrica, mejor cabeza de serie del torneo, c...",9.12,fleurs:es_419,,dev
10,fleurs_es_419_0010,NaN,data/raw/audio/fleurs_es_419_0010.wav,Ninguna alianza aérea abarca el cruce de los t...,9.78,fleurs:es_419,,dev
11,fleurs_es_419_0011,NaN,data/raw/audio/fleurs_es_419_0011.wav,Existen cámaras de películas con formato medio...,10.44,fleurs:es_419,,dev
12,fleurs_es_419_0012,NaN,data/raw/audio/fleurs_es_419_0012.wav,"El Sr. Costello sostuvo que, cuando la generac...",9.42,fleurs:es_419,,dev
13,fleurs_es_419_0013,NaN,data/raw/audio/fleurs_es_419_0013.wav,La luz y el calor que emana de las estrellas s...,12.60,fleurs:es_419,,test
14,fleurs_es_419_0014,NaN,data/raw/audio/fleurs_es_419_0014.wav,"Por suerte, estoy bien, pero presencié una esc...",9.36,fleurs:es_419,,dev
15,fleurs_es_419_0015,NaN,data/raw/audio/fleurs_es_419_0015.wav,Si quiere viajar alrededor del mundo circunscr...,12.36,fleurs:es_419,,dev
16,fleurs_es_419_0016,NaN,data/raw/audio/fleurs_es_419_0016.wav,«Algunos estudios sugieren que la enfermedad d...,10.56,fleurs:es_419,,dev
17,fleurs_es_419_0017,NaN,data/raw/audio/fleurs_es_419_0017.wav,El juez le manifestó a Blake que era «práctica...,8.94,fleurs:es_419,,test
18,fleurs_es_419_0018,NaN,data/raw/audio/fleurs_es_419_0018.wav,"Otra figura griega de renombre es Pitágoras, m...",12.66,fleurs:es_419,,dev
19,fleurs_es_419_0019,NaN,data/raw/audio/fleurs_es_419_0019.wav,"Por otra parte, es precisamente debido al elev...",9.48,fleurs:es_419,,dev

**Resultado esperado de esta fase:** `evaluation_v1.csv` es el dataset dorado con 20 muestras, listo para ser validado en el notebook 03. Su objetivo posterior es evaluar ASR (WER), traducción (BLEU/COMET) y voice cloning; **no** es el corpus de entrenamiento del traductor.

In [ ]:
# Actualizar el repositorio desde GitHub (opcional, cuando lo desees).
# No se ejecuta automáticamente para no sobrescribir artefactos generados durante la sesión.
# !git pull --ff-only